// API Method constants
export const API_METHOD = {
  categories: '/api/categories',
  products: '/api/products',
  metals: '/api/metals',
  stones: '/api/stones',
  orders: '/api/orders',
  customers: '/api/customers',
  analytics: '/api/analytics',
  reviews: '/api/reviews',
  favorites: '/api/favorites',
  settings: '/api/settings',
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
    changePassword: '/api/auth/change-password',
    refreshToken: '/api/auth/refresh-token',
    logout: '/api/auth/logout',
    profile: '/api/auth/profile',
    updateProfile: '/api/auth/profile',
  },
  cart: '/api/cart',
};
